"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Kreye chemen ki andedan pwojè a tankou sa: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Paramèt devlopman rapid - pa apwopriye pou pwodiksyon
# Gade https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# AVIS SEKIRITE: kenbe kle sekretè yo itilize nan pwodiksyon an sekrè!
SECRET_KEY = 'YOUR_SECRET_KEY_HERE'

# AVIS SEKIRITE: pa kouri avèk debug aktif nan pwodiksyon!
DEBUG = True

# Lis adrès ki pèmèt aksè nan sit la
ALLOWED_HOSTS = [".replit.dev", ".replit.app"]

# Lis domèn ki fè konfyans pou CSRF (Cross-Site Request Forgery)
CSRF_TRUSTED_ORIGINS = ["https://*.replit.dev", "https://*.replit.app"]

# Definisyon aplikasyon yo

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'django_moncash'  # Ajoute aplikasyon MonCash
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Chemen pou modèl yo si ou ajoute yo
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Konfigirasyon baz done
# Gade https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Itilize SQLite kòm baz done
        'NAME': BASE_DIR / 'db.sqlite3',  # Chemen baz done a
    }
}

# Konfigirasyon MonCash API (chèche kle yo nan anviwònman pwodiksyon)
MONCASH = {
    'CLIENT_ID': 'YOUR_CLIENT_ID_HERE',
    'SECRET_KEY': 'YOUR_SECRET_KEY_HERE',
    'ENVIRONMENT': 'sandbox'  # Pou tès; chanje nan 'live' pou pwodiksyon
}

# Validasyon modpas
# Gade https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Entènasyonalizasyon
# Gade https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Kòd langaj default

TIME_ZONE = 'UTC'  # Zòn tan default

USE_I18N = True

USE_TZ = True

# Fichye statik (CSS, JavaScript, Imaj)
# Gade https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  # URL pou fichye statik yo

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # Chemen pou fichye statik yo
]

# Default primary key field type
# Gade https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sekirite pou X-Frame-Options
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
